# This is a basic workflow to help you get started with Actions

name: simple_deployment_pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # use nodejs v.12.x as with planned production env
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # install dependencies from package.json
      - name: npm install 
        run: npm install  

      # update caniuse-lite 
      - name: npx browserslist@latest --update-db
        run: npx browserslist@latest --update-db
        
      # run eslint
      - name: lint
        run: npm run eslint
        
      #run build 
      - name: build
        run: npm run build

      #run test
      - name: test
        run: npm run test

      
